# Generated by Django 4.2.3 on 2023-12-06 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='tableros_permitidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
